# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lend
  # add all pods for Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'

  target 'LendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LendUITests' do
    # Pods for testing
  end

end
