# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'Lend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lend
  # add all pods for Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage', '~> 8.0'
  pod 'FirebaseFirestoreSwift'
  pod 'CodableFirebase'
  
  #pods for google maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  #pod for image downloading and caching
  pod 'Kingfisher', '~> 5.0'
  
  #pod for review stars
  pod 'Cosmos', '~> 21.0'
  
  #pod for building forms
  pod 'Eureka'


  target 'LendTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LendUITests' do
    # Pods for testing
  end

end
